# Generated by Django 5.1.6 on 2025-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_centers/'),
        ),
    ]
