# Generated by Django 5.1.6 on 2025-03-06 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servicecenter_description_servicecenter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('selected_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicecenter')),
            ],
        ),
    ]
